stages:          # 定义执行的阶段顺序
  - test

variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer"

cache:
  paths:
    - vendor/
    - $COMPOSER_CACHE_DIR

build-job:       # 安装依赖
  image: php:8.3
  stage: test
  before_script:
    - apt-get update && apt-get install -y git unzip libzip-dev
    - docker-php-ext-install zip
    - php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
  script:
    - composer install --prefer-dist --no-progress
  retry:
    max: 2
    when: script_failure

unit-test-job:   
  image: php:8.3
  stage: test
  script:
    - XDEBUG_MODE=coverage ./vendor/bin/pest --coverage-text --colors=never
  retry:
    max: 1
    when: always
  artifacts:
    when: always
    paths:
      - junit.xml
      - cobertura.xml
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: 'cobertura'
        path: cobertura.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
